services:

  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    container_name: watchtower
    command: --interval 30 pihole watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "5555:8080"

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      VIRTUAL_HOST: pihole
      FTLCONF_LOCAL_IPV4: 192.168.0.33
      PROXY_LOCATION: 192.168.0.33:80
      VIRTUAL_PORT: 80
      TZ: Europe/Berlin  # Set your timezone here
#      WEBPASSWORD: f4x4d8p6  # Password for the Pi-hole admin interface
    volumes:
      - /opt/ceph/piHole/etc-pihole:/etc/pihole
      - /opt/ceph/piHole/etc-dnsmasq.d:/etc/dnsmasq.d
#    ports:
#      - "53:53/tcp"
#      - "53:53/udp"
#      - "67:67/udp"
#      - "80:80/tcp"
#      - "443:443/tcp"
    restart: unless-stopped
    network_mode: 'host'
    dns:
      - 127.0.0.1
      - 1.1.1.1  # Or another DNS server of your choice
    cap_add:
      - NET_ADMIN  # Required to configure networking

  openhab:
    image: "openhab/openhab:latest-alpine"
    container_name: openhab
    restart: unless-stopped
    ports:
      - "8080:8080"      # OpenHAB main UI port
      - "8443:8443"      # OpenHAB HTTPS port
      - "5007:5007"      # OpenHAB remote console port
    environment:
      TZ: "Europe/Berlin"  # Replace with your timezone
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      USER_ID: "9001"    # Adjust user ID if necessary
      GROUP_ID: "9001"   # Adjust group ID if necessary
      CRYPTO_POLICY: "unlimited"
    volumes:
      - "/opt/ceph/openhab/addons:/openhab/addons"     # Mount for additional bindings and addons
      - "/opt/ceph/openhab/conf:/openhab/conf"         # Configuration files (e.g., rules, items, sitemap)
      - "/opt/ceph/openhab/userdata:/openhab/userdata" # Persistent data
    depends_on:
      - mosquitto

  mosquitto:
    image: "eclipse-mosquitto:latest"
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"      # MQTT port for clients
      - "9001:9001"      # WebSocket port for MQTT over WebSocket (optional)
    volumes:
      - "/opt/ceph/mosquitto/config:/mosquitto/config"   # Config files for Mosquitto
      - "/opt/ceph/mosquitto/data:/mosquitto/data"       # Persistence data for Mosquitto
      - "/opt/ceph/mosquitto/log:/mosquitto/log"         # Log files for Mosquitto