- name: Create a new Proxmox VM and Configure HA for node1
  hosts: proxmox_nodes
  gather_facts: false
  vars:
    vm_id: "{{ hostvars[inventory_hostname]['vm_id'] }}"
    vm_ip: "{{ hostvars[inventory_hostname]['vm_ip'] }}"
    vm_password: "{{ hostvars[inventory_hostname]['vm_password'] }}"
    ubuntu_name: "{{ hostvars[inventory_hostname]['ubuntu_name'] }}" # Define ubuntu_name from inventory.ini
  tasks:
    - name: Check if VM exists
      command: "qm status {{ vm_id }}"
      register: vm_status
      ignore_errors: true

    - name: Create the VM with initial settings
      command: "qm create {{ vm_id }} --memory 4096 --name {{ ubuntu_name }} --net0 virtio,bridge=vmbr0 --cores 6 --machine q35 --bios ovmf"
      when: vm_status.rc != 0

    - name: Import the disk image for the VM
      command: "qm importdisk {{ vm_id }} /var/lib/vz/template/iso/ubuntu-24.04-server-cloudimg-amd64.img cephpool"
      when: vm_status.rc != 0

    - name: Set OS type to Linux
      command: "qm set {{ vm_id }} --ostype l26"
      when: vm_status.rc != 0

    - name: Enable QEMU guest agent
      command: "qm set {{ vm_id }} --agent enabled=1"
      when: vm_status.rc != 0

    - name: Set up SCSI controller
      command: "qm set {{ vm_id }} --scsihw virtio-scsi-single"
      when: vm_status.rc != 0

    - name: Add a new 16GB SCSI disk
      command: "qm set {{ vm_id }} --scsi0 cephpool:vm-{{ vm_id }}-disk-0,discard=on,iothread=1"
      when: vm_status.rc != 0

    - name: Add cloud-init disk and configure boot options
      command: "qm set {{ vm_id }} --ide2 cephpool:cloudinit"
      when: vm_status.rc != 0

    - name: Configure boot device
      command: "qm set {{ vm_id }} --boot c --bootdisk scsi0"
      when: vm_status.rc != 0

    - name: Set up EFI disk for UEFI boot
      command: "qm set {{ vm_id }} --efidisk0 cephpool:1"
      when: vm_status.rc != 0

    - name: Enable cloud-init upgrade
      command: "qm set {{ vm_id }} --ciupgrade 0"
      when: vm_status.rc != 0

    - name: Set cloud-init user
      command: "qm set {{ vm_id }} --ciuser dhiego"

    - name: Set cloud-init password
      command: "qm set {{ vm_id }} --cipassword !Ds21032962"

    - name: Add SSH keys to cloud-init
      block:
        - name: Create SSH keys file
          copy:
            content: |
              ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCzz/yPx8rC1KsnXm+PkEogIZfrjRWiQvPk/ngD4Ol723de8SDhV8PCo/AloZYp3SiYz3aIoKKgr6C4iUcxxsKTWCTdPLQLISuOoenYDoxgXw74gg6Ulsc5FBdyojOANbL9UVObNiBMhQvlXj4iomDB6Mbgi0fU6h1JoVMIR2/DD0mff/1o0T+ycIbEx/tK6ScY+jh3tMBxU/rnCESF81/WLeOArp9UkhmqpQOS26VKLn4W8ml0HQZ4oMublztiguMZ0p2hMfiU3IbfXGz+JrGyeKi4gV6D8lal9EFRN7B7mTr3fzMkw+gb3MTleckAP1ITyfKlEU26n0dcVyywHWaLKVn4Zu/Xa6Tt7c4NE8LnuWSkNTie8uhRW+rVbQ8kk72XiW0GAxoO1iVGzljmIh4Lw3DDLhp9wp5ACI/4NJMlOJmLPfuyMh5F0Er891a21D+yKskgEml8tPB37JchGPW7IRxYYQS6g79PWE3n2aMAQxGPzeUgVRaGziCJIMrCq5mgzbN255vB5NzsBAwqRbpQqcXql+N0FVVyMP4pNYF2sh8Gii1wn2MrB7cye22Y3sZvUumUE0f26F55dUJZ116vThdh9mbsMnWZlk3+bTTUSSLfrDObc0aS6/FDxsjov01vWxzCm8K7Qd/QlQNPpJlhxo+keuA7kcrQLjtqPPeS+Q== dhiego.silva@hotmail.com
              ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCbc8uz/GZuGU1a8vGrocddM9jDjzODH2nDBsZt3ZDWWeicdKWFj0OP+fpzFAn2+qYXpBdRrEPq3SX/SncZUJCgYtQOBqPRr9nr/eaOPP4w8OCnQqmgJnksFyEK4nzPrJEFjUmmULLBUtA41iS9hhnuc8ZCpX948MuoOCttZUzfJAd31smqCJauhCI7+rQ8zs+2NnKzFaFyFchmfXbpA/Djir5+4ga5zl6lhvDOF6u/jAp4WiU3+y3BryH00pSwaEjyDVciRt5Yt8ZPTGXiZmuuY7f2tVGJBR36PwgDubs1BH1qEk27pYL3d6HcuQoBuwpE0VZur7AGasYyWZ6XJAAVlfw4/VwTaEnffjiIe7zlacZseXdaBtGh0v/J7doqRH0sIZOLvqjYOrIp1i/xpr+6mWkWxgyCqxZppfbwt0YBzF9huWQxCBW254WzkkTyKEZpKZrZzrHbLC+O7ZuBDzAQ546ZfZA733G5DREAlmXuCDoCNAP6GQ0pWdvh86xGEFmr49KHXJWDyUdBKVti92yrhdcAZ/5ODf8LnZ8EkpG2ZLsHXDPtNgmg5PcGTw3YHFgWMIxjPE4SfVEJzXsde5Lay9l0K3MEQg0+UUxjQk0gE0bdXJZZptxkwEERNG73Y52XC9bq7RBhwZie8iExLNRuWQ7CFZ8upOe4FfOmau9Y3Q== root@home
              ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9q7n5v91tGVYyrLC73D7wlmdqyj+Zdji6Cu/b0yO4Dq1cvCDyBLETK23xVFrpOrGJ3KPAiLWNg624yRCz4pFxB1vSBGi2fkM/CYNydZBgvWG6DyKMPkCzQ8EW42s5fQB88/DV5bnoha+UTN8IRcjVU/5/q/nvy0rEwIKE8jFGzZm0a/tckpiBkhpyl/eIPAU034URhJxifRztJ2oyHFczCr3SttdFZT6UqBy4MWkVsddzPMKet2otI6UAa5d0BktbxEbxJaDFKiU3LCNiiS72svtMdPAaOZ4CUjc4vXyUKwsciJW5EyoOxLJ57FmjKddSYj89/jY+mjfHWII+L0ZUuqNayTHr89nuz3Xm6gkMGP8W9ism7RCemta6UcsUjZ/Na0SFrRWzX5CJ6vpN+EQ4XLTt6PH/+34+n4M1R8A7ePErpakJo7Nx0EJwz0lTM5yySYTdokx/5Q6ygg29NX4tbz2loyNAJ6qXsuR8/FZKQ0in4hOmwWx6cqB9vouCshfnubklEZ0mgd0jbjNYvuDKzeLKMySkcdoreMoJbGgPaxtow1aFNjVvM4V5gf3MElCKvINcA2rC491i6Byfo0OvkrV+3FjHADED9z8HpFXwKzZ+nA0tXAKRf1Nz0Hq5Lg1sxoq15NNur4JwyCS9Btb5hURfzpPD9O7qSA1VmJ/Dkw== root@ansibleserver
              ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5UiPBEbSf2Jdh/jNJNstQp+QFX7pp3Pk/C68TKjylnRlZXgGgW1vNirz/lmGdLkilcVivL5eCkuwRX2W9OOP6QwB4KOE3tIkO4x4VxhVtnLkI4ZDG17/e1bhu/2XGvjuIkCgAEo0HCHd/yU7NzC4p06sf8QCaT77eIDO501ASUzpuOCOuTnas4gKLQ1sJNsoGux9gr2V159hT1F8DnImsnj9UC6iQd3X+YVQQ2YTRwRCIO6oF5XUkdIRlR6MayMXHEgfDZ/c4NDDyTkilY9qNrp1Gad2C8AYGOLfHIJTggUafkyDgHuZJpmno9GkRY2Xo2luRr2RPMgBcvzHwbzvYWtYa57j5gzHAU4HnAhp1rvcrmx6NPPcVCdQLPHzYDhApGCH2Gj4smcT+LGGlzZ3gjdZjizZ+sjOHE4TnMAJ2G4tLKvYycCCSk2I1RBH2istLf6qeL8wcA5jYemlVtzGbp/zz8XaXqvf260wWMM+kkjO+NYrM9E1y88BBBZsqhziuG0EW3whT4W03Xj28jXjxtCFVWHLDxr3fQnq18eFhzMK7q9E5e3Q2mS/vpY1NXXePUnG9EV8xlu5bmRr1yEdmxC2U2TmJFajRtWZAq4MP917rvggyzT/EuE8QMhpazUztakJadWHC2CJBHB6k+BxyfY8w0P2l3KFmi9+/p8SM2Q== dhiego.silva@hotmail.com
            dest: /tmp/ssh_keys.txt

        - name: Set SSH keys in VM
          command: "qm set {{ vm_id }} --sshkeys /tmp/ssh_keys.txt"

        - name: Remove temporary SSH keys file
          file:
            path: /tmp/ssh_keys.txt
            state: absent

    - name: Set IP configuration for the VM
      command: "qm set {{ vm_id }} --ipconfig0 ip={{ vm_ip }}/24,gw=192.168.0.1"

    # High Availability Configuration
    - name: Add node1 to HA Manager (High Availability Group)
      command: "ha-manager add vm:{{ vm_id }} --comment 'HA setup for node1'"
      when: inventory_hostname == 'node1'

    - name: Set high availability properties for node1
      command: "ha-manager set vm:{{ vm_id }} --max_restart 3 --state started"
      when: inventory_hostname == 'node1'

    - name: Resize the SCSI disk to 16GB
      command: "qm resize {{ vm_id }} scsi0 16G"

    - name: Verify HA configuration for node1
      command: "ha-manager status"
      register: ha_status
      when: inventory_hostname == 'node1'

    - name: Display HA status for node1
      debug:
        msg: "HA Status: {{ ha_status.stdout }}"
      when: inventory_hostname == 'node1' and ha_status is defined
