---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-repmgr
  labels:
    app: postgresql-repmgr
spec:
  serviceName: postgresql-repmgr-headless
  replicas: 2
  selector:
    matchLabels:
      app: postgresql-repmgr
  template:
    metadata:
      labels:
        app: postgresql-repmgr
    spec:
      containers:
      - name: postgresql-repmgr
        image: bitnami/postgresql-repmgr:17
        env:
        - name: POSTGRESQL_REPLICATION_MODE
          value: "master"
        - name: POSTGRESQL_USERNAME
          value: "dhiego"
        - name: POSTGRESQL_PASSWORD
          value: "f4x4d8p6"
        - name: POSTGRESQL_DATABASE
          value: "metabase"
        - name: POSTGRESQL_REPLICATION_USER
          value: "repl_dhiego"
        - name: POSTGRESQL_REPLICATION_PASSWORD
          value: "f4x4d8p6"
        - name: REPMGR_PARTNER_NODES
          value: "postgresql-repmgr-0.postgresql-repmgr-headless,postgresql-repmgr-1.postgresql-repmgr-headless"
        - name: REPMGR_PRIMARY_HOST
          value: "postgresql-repmgr-0.postgresql-repmgr-headless"
        - name: REPMGR_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: REPMGR_NODE_NETWORK_NAME
          value: "$(HOSTNAME).postgresql-repmgr-headless"
        - name: REPMGR_USERNAME
          value: "dhiego"
        - name: REPMGR_PASSWORD
          value: "f4x4d8p6"
        ports:
        - name: postgresql
          containerPort: 5432
        volumeMounts:
        - name: postgresql-data
          mountPath: /bitnami/postgresql
  volumeClaimTemplates:
  - metadata:
      name: postgresql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "microk8s-hostpath"  # Updated to use the existing StorageClass
      resources:
        requests:
          storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgpool
  labels:
    app: pgpool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgpool
  template:
    metadata:
      labels:
        app: pgpool
    spec:
      containers:
      - name: pgpool
        image: bitnami/pgpool:latest
        env:
        - name: PGPOOL_BACKEND_NODES
          value: "0:postgresql-repmgr-0.postgresql-repmgr-headless:5432,1:postgresql-repmgr-1.postgresql-repmgr-headless:5432"
        - name: PGPOOL_SR_CHECK_USER
          value: "postgres"
        - name: PGPOOL_SR_CHECK_PASSWORD
          value: "f4x4d8p6"
        - name: PGPOOL_POSTGRES_USERNAME
          value: "dhiego"
        - name: PGPOOL_POSTGRES_PASSWORD
          value: "f4x4d8p6"
        - name: PGPOOL_ADMIN_USERNAME
          value: "admin"
        - name: PGPOOL_ADMIN_PASSWORD
          value: "f4x4d8p6"
        ports:
        - name: pgpool
          containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-repmgr-headless
  labels:
    app: postgresql-repmgr
spec:
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None
  selector:
    app: postgresql-repmgr
---
apiVersion: v1
kind: Service
metadata:
  name: pgpool-service
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: pgpool
