---
- name: Setup Alpine Linux for Docker, Docker Compose, and Automated Upgrades
  hosts: alpine
  become: true

  tasks:
    - name: Update repository to use the latest stable Alpine packages
      ansible.builtin.lineinfile:
        path: /etc/apk/repositories
        regexp: '^https://dl-cdn.alpinelinux.org/alpine/v[0-9\.]+/main$'
        line: 'https://dl-cdn.alpinelinux.org/alpine/latest-stable/main'
        state: present
      register: main_repo

    - name: Update community repository to use the latest stable Alpine packages
      ansible.builtin.lineinfile:
        path: /etc/apk/repositories
        regexp: '^https://dl-cdn.alpinelinux.org/alpine/v[0-9\.]+/community$'
        line: 'https://dl-cdn.alpinelinux.org/alpine/latest-stable/community'
        state: present
      register: community_repo

    - name: Run apk update if repositories were modified
      ansible.builtin.command: apk update
      when: main_repo.changed or community_repo.changed

    - name: Install Docker and Docker Compose
      ansible.builtin.apk:
        name:
          - docker
          - docker-compose
        update_cache: yes
        state: latest

    - name: Enable Docker service to start on boot
      ansible.builtin.service:
        name: docker
        enabled: true

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started

    - name: Create a script to auto-upgrade and reboot if needed
      ansible.builtin.copy:
        dest: /usr/local/bin/auto_upgrade.sh
        mode: '0755'
        content: |
          #!/bin/sh
          # Update the package index
          apk update
          # Perform the upgrade
          if apk upgrade --available | grep -q "Upgraded"; then
            # If packages were upgraded, reboot
            echo "System upgraded, rebooting..."
            reboot
          else
            echo "No upgrades performed."
          fi

    - name: Schedule weekly cron job for auto-upgrade script
      ansible.builtin.cron:
        name: "Weekly auto-upgrade for Alpine Linux"
        job: "/usr/local/bin/auto_upgrade.sh"
        weekday: "0"  # Sunday
        hour: "3"     # 3:00 AM
        user: root
        state: present

    - name: Create Docker Compose file
      ansible.builtin.copy:
        dest: /opt/docker-compose.yml
        content: |
          services:

            watchtower:
              image: containrrr/watchtower:latest
              restart: unless-stopped
              container_name: watchtower
              environment:
                - WATCHTOWER_CLEANUP=true
                - WATCHTOWER_INCLUDE_RESTARTING=true
                - WATCHTOWER_POLL_INTERVAL=3600
              volumes:
                - /var/run/docker.sock:/var/run/docker.sock
                - /etc/timezone:/etc/timezone:ro
              ports:
                - "5555:8080"

            pihole:
              container_name: pihole
              image: pihole/pihole:latest
              hostname: piholedhiego
              environment:
                - TZ=Europe/Berlin
                - VIRTUAL_HOST=piholedhiego.duckdns.org
                - PROXY_LOCATION=piholedhiego.duckdns.org
                - VIRTUAL_PORT=80
                - PIHOLE_DNS_1=1.1.1.1  # Use primary DNS
                - PIHOLE_DNS_2=8.8.8.8  # Use secondary DNS
                - FTLCONF_webserver_api_password=f4x4d8p6
                - DNSMASQ_LISTENING=all  # Ensure it listens to all interfaces
              volumes:
                - /opt/ceph/piHole/etc-pihole:/etc/pihole
                - /opt/ceph/piHole/etc-dnsmasq.d:/etc/dnsmasq.d
              network_mode: 'host'
              restart: unless-stopped
              dns:
                - 127.0.0.1
                - 1.1.1.1  # Or another DNS server of your choice
              cap_add:
                - NET_ADMIN  # Required to configure networking

            openhab:
              image: "openhab/openhab:latest-alpine"
              container_name: openhab
              restart: unless-stopped
              ports:
                - "8080:8080"      # OpenHAB main UI port
                - "8443:8443"      # OpenHAB HTTPS port
                - "5007:5007"      # OpenHAB remote console port
              environment:
                TZ: "Europe/Berlin"  # Replace with your timezone
                OPENHAB_HTTP_PORT: "8080"
                OPENHAB_HTTPS_PORT: "8443"
                USER_ID: "9001"    # Adjust user ID if necessary
                GROUP_ID: "9001"   # Adjust group ID if necessary
                CRYPTO_POLICY: "unlimited"
              volumes:
                - "/opt/ceph/openhab/addons:/openhab/addons"     # Mount for additional bindings and addons
                - "/opt/ceph/openhab/conf:/openhab/conf"         # Configuration files (e.g., rules, items, sitemap)
                - "/opt/ceph/openhab/userdata:/openhab/userdata" # Persistent data
              depends_on:
                - mosquitto

            mosquitto:
              image: "eclipse-mosquitto:latest"
              container_name: mosquitto
              restart: unless-stopped
              ports:
                - "1883:1883"      # MQTT port for clients
                - "9001:9001"      # WebSocket port for MQTT over WebSocket (optional)
              volumes:
                - "/opt/ceph/mosquitto/config:/mosquitto/config"   # Config files for Mosquitto
                - "/opt/ceph/mosquitto/data:/mosquitto/data"       # Persistence data for Mosquitto
                - "/opt/ceph/mosquitto/log:/mosquitto/log"         # Log files for Mosquitto

    - name: Start Docker Compose
      ansible.builtin.command:
        cmd: "docker-compose -f /opt/docker-compose.yml up -d"
        chdir: /opt


    - name: Ensure Docker Compose is restarted if Compose file changes
      ansible.builtin.command:
        cmd: "docker-compose -f /opt/docker-compose.yml restart"
        chdir: /opt
      when: "docker_compose_file_changed is defined and docker_compose_file_changed"
