- name: Configure Ubuntu 24.10 Environment
  hosts: all
  become: true
  tasks:

    - name: Set IP address, gateway, and DNS settings
      ansible.builtin.copy:
        content: |
          network:
            version: 2
            ethernets:
              enp0s3:
                dhcp4: no
                addresses: [192.168.0.100/24]
                gateway4: 192.168.0.1
                nameservers:
                  addresses: [192.168.0.33]
        dest: /etc/netplan/01-netcfg.yaml
      notify: Apply network changes

    - name: Check if snap is installed
      ansible.builtin.command: "command -v snap"
      register: snap_check
      ignore_errors: true

    - name: Stop snapd service to enable removal of core snaps
      ansible.builtin.systemd:
        name: snapd
        state: stopped
        enabled: no
      when: snap_check.rc == 0

    - name: Remove all non-core snap packages
      ansible.builtin.shell: |
        for snap in $(snap list | grep -v 'Name\|core\|snapd' | awk '{print $1}'); do
          snap remove --purge "$snap" || true
        done
      ignore_errors: true
      register: snap_remove_noncore_result
      when: snap_check.rc == 0

    - name: Remove core snap packages
      ansible.builtin.shell: |
        snap remove --purge snapd-desktop-integration || true
        snap remove --purge snap-store || true
        snap remove --purge core22 || true
      ignore_errors: true
      when: snap_remove_noncore_result is succeeded and snap_check.rc == 0

    - name: Remove snap completely from the system
      ansible.builtin.apt:
        name: snapd
        state: absent
      when: snap_remove_noncore_result is succeeded and snap_check.rc == 0

    - name: Upgrade all packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Install flatpak
      ansible.builtin.apt:
        name: flatpak
        state: present

    - name: Install flatpak repository (Flathub)
      ansible.builtin.command: "flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo"
      args:
        creates: /var/lib/flatpak/repo/flathub

    - name: Install Brave Browser via Flatpak
      ansible.builtin.command: "flatpak install -y flathub com.brave.Browser"
      args:
        creates: /var/lib/flatpak/app/com.brave.Browser

    - name: Install PeaZip via Flatpak
      ansible.builtin.command: "flatpak install -y flathub io.github.peazip.PeaZip"
      args:
        creates: /var/lib/flatpak/app/io.github.peazip.PeaZip

    - name: Install Flatseal via Flatpak
      ansible.builtin.command: "flatpak install -y flathub com.github.tchx84.Flatseal"
      args:
        creates: /var/lib/flatpak/app/com.github.tchx84.Flatseal

    - name: Install VLC via Flatpak
      ansible.builtin.command: "flatpak install -y flathub org.videolan.VLC"
      args:
        creates: /var/lib/flatpak/app/org.videolan.VLC

    - name: Install Meld via Flatpak
      ansible.builtin.command: "flatpak install -y flathub org.gnome.meld"
      args:
        creates: /var/lib/flatpak/app/org.gnome.meld

    - name: Install DBeaver Community via Flatpak
      ansible.builtin.command: "flatpak install -y flathub io.dbeaver.DBeaverCommunity"
      args:
        creates: /var/lib/flatpak/app/io.dbeaver.DBeaverCommunity

    - name: Install Visual Studio Code via .deb package
      ansible.builtin.shell: |
        wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
        sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | sudo tee /etc/apt/sources.list.d/vscode.list
        sudo apt-get install apt-transport-https -y
        sudo apt-get update
        sudo apt-get install code -y
      args:
        creates: /usr/bin/code

    - name: Install Remmina via Flatpak
      ansible.builtin.command: "flatpak install -y flathub org.remmina.Remmina"
      args:
        creates: /var/lib/flatpak/app/org.remmina.Remmina

    - name: Allow root login via SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin yes'
        state: present

    - name: Permit password authentication for SSH
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication yes'
        state: present

    - name: Restart SSH service
      ansible.builtin.systemd:
        name: sshd
        state: restarted

    - name: Set root password
      ansible.builtin.shell: |
        echo 'root:f4x4d8p6' | chpasswd

    - name: Remove gnome-power-manager, evince, and gnome-logs
      ansible.builtin.apt:
        name:
          - gnome-power-manager
          - evince
          - gnome-logs
        state: absent

    - name: Install Fish shell
      ansible.builtin.apt:
        name: fish
        state: present

    - name: Set Fish shell as default for all users
      ansible.builtin.shell: |
        chsh -s /usr/bin/fish $(whoami)

    - name: Configure Fish shell as default at startup
      ansible.builtin.lineinfile:
        path: /etc/passwd
        regexp: '^(.*?):(.*?):(.*?):(.*?):(.*?):(.*?):/bin/bash$'
        line: '\1:\2:\3:\4:\5:\6:/usr/bin/fish'
        state: present

    - name: Install GNOME Software
      ansible.builtin.apt:
        name: gnome-software
        state: present

    - name: Install GNOME Software Flatpak plugin
      ansible.builtin.apt:
        name: gnome-software-plugin-flatpak
        state: present

  handlers:
    - name: Apply network changes
      ansible.builtin.command: "netplan apply"
