---
- name: Setup Alpine Linux for Ansible
  hosts: all
  become: true
  vars:
    venv_path: /root/ansible-env
    profile_path: /root/.profile

  tasks:
    - name: Update repository to use the latest stable Alpine packages
      ansible.builtin.lineinfile:
        path: /etc/apk/repositories
        regexp: '^https://dl-cdn.alpinelinux.org/alpine/v[0-9\.]+/main$'
        line: 'https://dl-cdn.alpinelinux.org/alpine/latest-stable/main'
        state: present
      register: main_repo

    - name: Update community repository to use the latest stable Alpine packages
      ansible.builtin.lineinfile:
        path: /etc/apk/repositories
        regexp: '^https://dl-cdn.alpinelinux.org/alpine/v[0-9\.]+/community$'
        line: 'https://dl-cdn.alpinelinux.org/alpine/latest-stable/community'
        state: present
      register: community_repo

    - name: Run apk update if repositories were modified
      ansible.builtin.command: apk update
      when: main_repo.changed or community_repo.changed

    - name: Install required packages
      ansible.builtin.package:
        name:
          - python3
          - py3-pip
          - py3-virtualenv
          - openssl
          - sshpass
        state: present

    - name: Install Ansible using pip3
      ansible.builtin.pip:
        name: ansible
        executable: pip3

    - name: Create a Python virtual environment
      ansible.builtin.command:
        cmd: python3 -m venv {{ venv_path }}
      args:
        creates: "{{ venv_path }}/bin/activate"

    - name: Add virtual environment activation to root profile
      ansible.builtin.lineinfile:
        path: "{{ profile_path }}"
        line: "source {{ venv_path }}/bin/activate"
        state: present

    - name: Install passlib using pip
      ansible.builtin.pip:
        name: passlib
        virtualenv: "{{ venv_path }}"

    - name: Install kubernetes Python package
      ansible.builtin.pip:
        name: kubernetes
        virtualenv: "{{ venv_path }}"

    - name: Install openshift Python package
      ansible.builtin.pip:
        name: openshift
        virtualenv: "{{ venv_path }}"

    - name: Install community.kubernetes Ansible collection
      ansible.builtin.command:
        cmd: "{{ venv_path }}/bin/ansible-galaxy collection install community.kubernetes"
