qm create 9000 --memory 2048 --name ubuntu-cloud --net0 virtio,bridge=vmbr0 --machine q35 --bios ovmf

qm importdisk 9000 /var/lib/vz/template/iso/ubuntu-24.04-server-cloudimg-amd64.img local-lvm

qm set 9000 --scsihw virtio-scsi-single
qm set 9000 --scsi0 local-lvm:vm-9000-disk-0,discard=on,iothread=1

qm set 9000 --ide2 local-lvm:cloudinit
qm set 9000 --boot c --bootdisk scsi0

qm set 9000 --efidisk0 local-lvm:1


qm set 9000 --ciuser dhiego --cipassword f4x4d8p4

qm set 9000 --ipconfig0 ip=192.168.0.55/24,gw=192.168.0.1

qm start 9000





qm create 9000 --memory 2048 --name ubuntu-cloud --net0 virtio,bridge=vmbr0 --machine q35 --bios ovmf && qm importdisk 9000 /var/lib/vz/template/iso/ubuntu-24.04-server-cloudimg-amd64.img local-lvm && qm set 9000 --scsihw virtio-scsi-single && qm set 9000 --scsi0 local-lvm:vm-9000-disk-0,discard=on,iothread=1 && qm set 9000 --ide2 local-lvm:cloudinit && qm set 9000 --boot c --bootdisk scsi0 && qm set 9000 --efidisk0 local-lvm:1 && qm set 9000 --ciuser dhiego --cipassword f4x4d8p4 && qm set 9000 --ipconfig0 ip=192.168.0.55/24,gw=192.168.0.1 && qm start 9000


#working
qm create 9000 --memory 2048 --name ubuntu-cloud --net0 virtio,bridge=vmbr0 --machine q35 --bios ovmf && qm importdisk 9000 /var/lib/vz/template/iso/ubuntu-24.04-server-cloudimg-amd64.img local-lvm && qm set 9000 --scsihw virtio-scsi-single --scsi0 local-lvm:vm-9000-disk-0,discard=on,iothread=1 --ide2 local-lvm:cloudinit --boot c --bootdisk scsi0 --efidisk0 local-lvm:1 && qm start 9000
