services:

  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=3600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "5555:8080"

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: piholedhiego
    environment:
      - TZ=Europe/Berlin
      - VIRTUAL_HOST=piholedhiego.duckdns.org
      - PROXY_LOCATION=piholedhiego.duckdns.org
      - VIRTUAL_PORT=80
      - PIHOLE_DNS_1=1.1.1.1  # Use primary DNS
      - PIHOLE_DNS_2=8.8.8.8  # Use secondary DNS
      - FTLCONF_webserver_api_password=f4x4d8p6
      - DNSMASQ_LISTENING=all  # Ensure it listens to all interfaces
    volumes:
      - /opt/ceph/piHole/etc-pihole:/etc/pihole
      - /opt/ceph/piHole/etc-dnsmasq.d:/etc/dnsmasq.d
    network_mode: 'host'
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 1.1.1.1  # Or another DNS server of your choice
    cap_add:
      - NET_ADMIN  # Required to configure networking
